"""Repository-bound Git execution policy.

Security requirement: Git >= 2.45 is required to suppress automatic promisor
fetches during object reads. Older Git silently ignores GIT_NO_LAZY_FETCH and
may execute repository-configured transports; binding alone does not make those
versions safe for untrusted partial clones. Explicit fetches use secure-fetch.
"""

from __future__ import annotations

from functools import cache
import os
from pathlib import Path
import re
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from git import Repo


_INVALID_REF_CHARACTER = re.compile(r"[\x00-\x20\x7f~^:?\\\[]")


# Only Chartreux-generated transport/config overrides may augment the binding.
_EXECUTION_GIT_KEYS = frozenset({
    "GIT_DIR",
    "GIT_COMMON_DIR",
    "GIT_NO_LAZY_FETCH",
    "GIT_NO_REPAIR",
    "GIT_WORK_TREE",
    "GIT_CONFIG_COUNT",
    "GIT_CONFIG_GLOBAL",
    "GIT_CONFIG_SYSTEM",
    "GIT_CONFIG_PARAMETERS",
    "GIT_ALLOW_PROTOCOL",
    "GIT_ASKPASS",
    "GIT_EXEC_PATH",
    "GIT_PROTOCOL_FROM_USER",
    "GIT_PROXY_COMMAND",
    "GIT_SSH",
    "GIT_SSH_COMMAND",
    "GIT_SSH_VARIANT",
    "GIT_TERMINAL_PROMPT",
})


# Inherited Git variables are not an API: only values generated by this module
# or the secure-fetch policy reach Git. This also excludes GIT_CONFIG,
# GIT_SHALLOW_FILE, GIT_REPLACE_REF_BASE and future repository-routing knobs.
def inherited_environment() -> dict[str, str]:
    return {
        key: value for key, value in os.environ.items() if not key.startswith("GIT_")
    }


def repository_environment(repo: Repo) -> dict[str, str]:
    env = inherited_environment()
    # Object readers must never invoke repository-configured promisor transports.
    # Explicit fetches still go through prepare_secure_fetch.
    env["GIT_NO_LAZY_FETCH"] = "1"
    env["GIT_NO_REPAIR"] = "1"
    env["GIT_DIR"] = str(Path(repo.git_dir).resolve())
    env["GIT_COMMON_DIR"] = str(Path(repo.common_dir).resolve())
    worktree = _repository_worktree(repo)
    if worktree is not None:
        env["GIT_WORK_TREE"] = str(worktree)
    return env


def _repository_worktree(repo: Repo) -> Path | None:
    if repo.bare:
        return None
    git_dir = Path(repo.git_dir).resolve()
    gitfile = git_dir / "gitdir"
    if (git_dir / "commondir").is_file() and gitfile.is_file():
        path = Path(gitfile.read_text().strip())
        return (path if path.is_absolute() else git_dir / path).resolve().parent
    # The opened checkout, not core.worktree, defines the execution boundary.
    # GitPython already preserves the opened path for separate-git-dir layouts.
    if git_dir.name == ".git":
        return git_dir.parent
    return Path(repo.working_dir).resolve()


def bind_repository(repo: Repo) -> None:
    """Bind all commands, including persistent cat-file children, to this Repo.

    GitPython 3.1.58 merges both handle and inline environments into os.environ;
    omission inherits, None is not a valid subprocess value, and empty routing
    paths are not equivalent to absence. POSIX env -u provides actual removal
    without changing process-global state or copying GitPython's executor.
    """
    from git import Git
    from git.db import GitCmdObjectDB

    if not isinstance(repo.git, Git) or isinstance(repo.git, _bound_git_type()):
        return
    worktree = _repository_worktree(repo)
    repo._working_tree_dir = str(worktree) if worktree is not None else None
    repo.working_dir = str(worktree or Path(repo.common_dir).resolve())
    command = _bound_git_type()(repo.working_dir)
    command.repository = repo
    repo.git.clear_cache()
    repo.git = command
    if isinstance(repo.odb, GitCmdObjectDB):
        repo.odb = GitCmdObjectDB(str(Path(repo.common_dir) / "objects"), command)


@cache
def _bound_git_type() -> Any:
    # Lazy import preserves startup on systems without Git.
    from git import Git

    class RepositoryGit(Git):
        repository: Repo

        def execute(self, command: Any, **kwargs: Any) -> Any:
            env = repository_environment(self.repository)
            env.update(self.environment())
            env.update(kwargs.pop("env", None) or {})
            for key in tuple(env):
                if (
                    key.startswith("GIT_")
                    and key not in _EXECUTION_GIT_KEYS
                    and not key.startswith(("GIT_CONFIG_KEY_", "GIT_CONFIG_VALUE_"))
                ):
                    del env[key]
            # Routing is always bound, even if an inline environment supplies it.
            bound = repository_environment(self.repository)
            for key in (
                "GIT_DIR",
                "GIT_COMMON_DIR",
                "GIT_WORK_TREE",
                "GIT_NO_LAZY_FETCH",
                "GIT_NO_REPAIR",
            ):
                env.pop(key, None)
                if key in bound:
                    env[key] = bound[key]
            launcher = next(
                (path for path in ("/usr/bin/env", "/bin/env") if Path(path).is_file()),
                None,
            )
            if launcher is None:
                raise RuntimeError("Repository-bound Git requires POSIX env")
            removals = [
                argument
                for key in os.environ.keys() | self.environment().keys()
                if key.startswith("GIT_") and key not in env
                for argument in ("-u", key)
            ]
            # Keep values out of argv (and GitPython's command/error logging).
            return cast(Any, super().execute)(
                [launcher, *removals, *command], env=env, **kwargs
            )

    return RepositoryGit


def validate_branch_name(branch: str) -> None:
    """Git check-ref-format --branch rules for literal names, without a child.

    Previous-checkout expansion (@{-n}) is intentionally not a literal branch.
    """
    if not isinstance(branch, str) or branch.startswith("-") or branch == "HEAD":
        raise ValueError(f"Invalid branch {branch!r}")
    validate_ref_name(f"refs/heads/{branch}")


def validate_ref_name(ref: str, *, pattern: bool = False) -> None:
    components = ref.split("/")
    invalid_spelling = any((
        not ref,
        ref == "@",
        ref.endswith("."),
        "/" not in ref,
        ".." in ref,
        "@{" in ref,
    ))
    if (
        invalid_spelling
        or _INVALID_REF_CHARACTER.search(ref)
        or any(
            not part or part.startswith(".") or part.endswith(".lock")
            for part in components
        )
        or ref.count("*") > (1 if pattern else 0)
    ):
        raise ValueError(f"Invalid ref {ref!r}")


def validate_fetch_refspec(refspec: str) -> None:
    """Accept explicit full-ref source:destination pairs, optionally forced/globbed."""
    value = refspec.removeprefix("+")
    if value.count(":") != 1:
        raise ValueError(f"Invalid fetch refspec {refspec!r}")
    source, destination = value.split(":")
    if not source.startswith("refs/") or not destination.startswith("refs/"):
        raise ValueError(f"Invalid fetch refspec {refspec!r}")
    validate_ref_name(source, pattern=True)
    validate_ref_name(destination, pattern=True)
    if source.count("*") != destination.count("*"):
        raise ValueError(f"Invalid fetch refspec {refspec!r}")
